version: '3'

services:
  authenticationDB2:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - dbdata:/var/lib/mysql
    ports:
     - 3307:3306
    networks:
      - admin
  authenticationDBMigration:
    image: authenticationdbmigration
    environment:
      - DATABASE_URL=authenticationDB2
    depends_on:
      authenticationDB2:
        condition: service_healthy
    networks:
      - admin
  authentication:
    image: authentication
    environment:
      - DATABASE_URL=authenticationDB2
    depends_on:
      - authenticationDBMigration
    ports:
      - 5002:5002
    networks:
      - admin
  adminer:
    image: adminer
    ports:
        - 8080:8080
    networks:
      - admin
  electionsdatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    ports:
      - 3308:3306
    networks:
      - admin
  electionDBMigration:
    image: electiondbmigration
    environment:
      - DATABASE_URL=electionsdatabase
    depends_on:
      electionsdatabase:
        condition: service_healthy
    networks:
      - admin
  admin:
    image: admin
    environment:
      - DATABASE_URL=electionsdatabase
    depends_on:
      - electionDBMigration
    ports:
      - 5001:5001
    networks:
      - admin
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - admin
  electionOfficial:
    image: electionofficial
    environment:
      - DATABASE_URL=electionsdatabase
    depends_on:
      - electionDBMigration
    ports:
      - 5000:5000
    networks:
      - admin
  daemon:
    image: daemon
    environment:
      - DATABASE_URL=electionsdatabase
    depends_on:
      - redis
      - electionDBMigration
    networks:
      - admin

volumes:
  dbdata:

networks:
  admin: