"""Production migration

Revision ID: eb9edc11cfbf
Revises: 
Create Date: 2021-09-10 01:30:02.055803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb9edc11cfbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('guid', table_name='votes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('guid', 'votes', ['guid'], unique=False)
    # ### end Alembic commands ###
